services:
  # Backend Web Service
  - type: web
    name: spendwise-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false # User will paste their MongoDB Atlas Connection URI here
        placeholder: "mongodb+srv://<username>:<password>@cluster0.xxxxx.mongodb.net/expense_tracker?retryWrites=true&w=majority"
      - key: JWT_SECRET
        generateValue: true # Render will auto-generate a secure cryptographically random key!

  # Frontend Static Site
  - type: web
    name: spendwise-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    headers:
      - key: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        src: /*
        dest: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: spendwise-backend
          property: host
